# coding: utf-8

# flake8: noqa
"""
    A sample API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Contact: standards-team@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ogcapi_processes_client.models.additional_parameter import AdditionalParameter
from ogcapi_processes_client.models.additional_parameter_value_inner import AdditionalParameterValueInner
from ogcapi_processes_client.models.bbox import Bbox
from ogcapi_processes_client.models.conf_classes import ConfClasses
from ogcapi_processes_client.models.description_type import DescriptionType
from ogcapi_processes_client.models.description_type_additional_parameters import DescriptionTypeAdditionalParameters
from ogcapi_processes_client.models.exception import Exception
from ogcapi_processes_client.models.execute import Execute
from ogcapi_processes_client.models.execute200_response import Execute200Response
from ogcapi_processes_client.models.execute_inputs_value import ExecuteInputsValue
from ogcapi_processes_client.models.format import Format
from ogcapi_processes_client.models.format_schema import FormatSchema
from ogcapi_processes_client.models.inline_or_ref_data import InlineOrRefData
from ogcapi_processes_client.models.input_description import InputDescription
from ogcapi_processes_client.models.input_description_all_of_max_occurs import InputDescriptionAllOfMaxOccurs
from ogcapi_processes_client.models.input_value import InputValue
from ogcapi_processes_client.models.input_value_no_object import InputValueNoObject
from ogcapi_processes_client.models.job_control_options import JobControlOptions
from ogcapi_processes_client.models.job_list import JobList
from ogcapi_processes_client.models.landing_page import LandingPage
from ogcapi_processes_client.models.link import Link
from ogcapi_processes_client.models.metadata import Metadata
from ogcapi_processes_client.models.model_schema import ModelSchema
from ogcapi_processes_client.models.output import Output
from ogcapi_processes_client.models.output_description import OutputDescription
from ogcapi_processes_client.models.process import Process
from ogcapi_processes_client.models.process_list import ProcessList
from ogcapi_processes_client.models.process_summary import ProcessSummary
from ogcapi_processes_client.models.qualified_input_value import QualifiedInputValue
from ogcapi_processes_client.models.reference import Reference
from ogcapi_processes_client.models.schema_one_of import SchemaOneOf
from ogcapi_processes_client.models.schema_one_of_additional_properties import SchemaOneOfAdditionalProperties
from ogcapi_processes_client.models.schema_one_of_not import SchemaOneOfNot
from ogcapi_processes_client.models.status_code import StatusCode
from ogcapi_processes_client.models.status_info import StatusInfo
from ogcapi_processes_client.models.subscriber import Subscriber
from ogcapi_processes_client.models.transmission_mode import TransmissionMode
