name: Package_n_Pypi

on:
  push:
    branches: [ "main", "develop" ]
  release:
    types: [published]
  pull_request:
    branches: [develop, main]
    
permissions:
  contents: read
  id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install hatch
    - name: Cache Hatch
      id: cache-hatch
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/share/hatch/env/virtual/
        key: ${{ runner.os }}-hatch
    - name: Build package
      run: cd src && hatch build
    - name: Publish package distributions to PyPI (main)
      if: github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
    - name: Publish package distributions to PyPI (non-main)
      if: github.ref != 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
